name: housecode
description: A set of extensions and widgets by Housecode.Net to simplify some function and re-useable widgets.
version: 1.0.4
homepage: https://github.com/housecode/housecode_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  universal_io: ^2.0.4
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
